DROP DATABASE IF EXISTS gymtech;
CREATE DATABASE gymtech;
USE gymtech;

-- Suppression dans l'ordre des dépendances
DROP TABLE IF EXISTS RESERVER;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS SALLES;
DROP TABLE IF EXISTS CAPTEURS;
DROP TABLE IF EXISTS EQUIPEMENTS;
DROP TABLE IF EXISTS COURS;
DROP TABLE IF EXISTS TYPE_USER;
DROP TABLE IF EXISTS TYPE_SALLE;
DROP TABLE IF EXISTS TYPE_CAPTEUR;

-- TYPE_CAPTEUR
CREATE TABLE TYPE_CAPTEUR (
   ID_TYPE_CAPTEUR CHAR(1) NOT NULL,
   LIBELLE_TYPE_CAPTEUR VARCHAR(50) NOT NULL,
   PRIMARY KEY (ID_TYPE_CAPTEUR)
);

-- TYPE_SALLE
CREATE TABLE TYPE_SALLE (
   ID_TYPE_SALLE CHAR(1) NOT NULL,
   LIBELLE_TYPE_SALLE VARCHAR(25),
   PRIMARY KEY (ID_TYPE_SALLE)
);

-- TYPE_USER
CREATE TABLE TYPE_USER (
   ID_TYPE_USER CHAR(1) NOT NULL,
   LIBELLE_TYPE_USER VARCHAR(25),
   PRIMARY KEY (ID_TYPE_USER)
);

-- CAPTEURS
CREATE TABLE CAPTEURS (
   ID_CAPTEUR INT NOT NULL AUTO_INCREMENT,
   ID_TYPE_CAPTEUR CHAR(1) NOT NULL,
   LIBELLE_CAPTEUR VARCHAR(50) NOT NULL,
   MESURE_1 FLOAT(3) NOT NULL,
   MESURE_2 FLOAT(3) NOT NULL,
   PRIMARY KEY (ID_CAPTEUR),
   FOREIGN KEY (ID_TYPE_CAPTEUR) REFERENCES TYPE_CAPTEUR(ID_TYPE_CAPTEUR)
);

-- COURS
CREATE TABLE COURS (
   ID_COURS INT NOT NULL AUTO_INCREMENT,
   TYPE_COURS VARCHAR(25) NOT NULL,
   DATE_COURS DATE NOT NULL,
   HEURE_DEBUT TIME NOT NULL,
   HEURE_FIN TIME NOT NULL,
   NOMBRE_PLACES INT NOT NULL,
   PRIMARY KEY (ID_COURS)
);

-- EQUIPEMENTS
CREATE TABLE EQUIPEMENTS (
   ID_EQUIPEMENT INT NOT NULL AUTO_INCREMENT,
   TYPE_EQUIPEMENT VARCHAR(25),
   QUANTITE_DISPONIBLE INT NOT NULL DEFAULT 0,
   PRIMARY KEY (ID_EQUIPEMENT)
);

-- SALLES
CREATE TABLE SALLES (
   ID_SALLE INT NOT NULL AUTO_INCREMENT,
   ID_TYPE_SALLE CHAR(1) NOT NULL,
   ID_CAPTEUR INT NOT NULL,
   NOM_SALLE VARCHAR(25),
   PRIMARY KEY (ID_SALLE),
   FOREIGN KEY (ID_TYPE_SALLE) REFERENCES TYPE_SALLE(ID_TYPE_SALLE),
   FOREIGN KEY (ID_CAPTEUR) REFERENCES CAPTEURS(ID_CAPTEUR)
);

-- USERS
CREATE TABLE USERS (
   ID_USER INT NOT NULL AUTO_INCREMENT,
   ID_SALLE INT NOT NULL,
   ID_TYPE_USER CHAR(1) NOT NULL,
   NOM_USER VARCHAR(25),
   PRENOM_USER VARCHAR(25),
   IDENTIFIANT_USER VARCHAR(50),
   GENRE_USER CHAR(1),
   MOT_DE_PASSE_USER CHAR(60),
   CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID_USER),
   FOREIGN KEY (ID_SALLE) REFERENCES SALLES(ID_SALLE),
   FOREIGN KEY (ID_TYPE_USER) REFERENCES TYPE_USER(ID_TYPE_USER)
);

-- RESERVER
CREATE TABLE RESERVER (
   ID_USER INT NOT NULL,
   ID_EQUIPEMENT INT,
   ID_COURS INT,
   DATE DATE,
   HEURE_DEBUT TIME,
   HEURE_FIN TIME,
   PRIMARY KEY (ID_USER, ID_EQUIPEMENT, ID_COURS, DATE, HEURE_DEBUT),
   FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER),
   FOREIGN KEY (ID_EQUIPEMENT) REFERENCES EQUIPEMENTS(ID_EQUIPEMENT),
   FOREIGN KEY (ID_COURS) REFERENCES COURS(ID_COURS)
);

-- TRIGGER: une réservation doit concerner soit un cours, soit un équipement, mais pas les deux
DELIMITER //
CREATE TRIGGER before_insert_RESERVER
BEFORE INSERT ON RESERVER
FOR EACH ROW
BEGIN
   IF (NEW.ID_COURS IS NOT NULL AND NEW.ID_EQUIPEMENT IS NOT NULL)
   OR (NEW.ID_COURS IS NULL AND NEW.ID_EQUIPEMENT IS NULL) THEN
      SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'Une réservation doit concerner soit un cours, soit un équipement, mais pas les deux';
   END IF;
END;//

-- TRIGGER: Vérifie disponibilité équipement
DELIMITER ;;

CREATE TRIGGER before_insert_reserver_check_dispo
BEFORE INSERT ON RESERVER
FOR EACH ROW
BEGIN
   DECLARE max_qty INT DEFAULT 0;
   DECLARE current_resa INT DEFAULT 0;

   IF NEW.ID_EQUIPEMENT IS NOT NULL THEN
      -- Récupère la quantité disponible pour cet équipement
      SELECT QUANTITE_DISPONIBLE INTO max_qty
      FROM EQUIPEMENTS
      WHERE ID_EQUIPEMENT = NEW.ID_EQUIPEMENT;

      -- Compte combien de réservations existent déjà sur ce créneau pour cet équipement
      SELECT COUNT(*) INTO current_resa
      FROM RESERVER
      WHERE ID_EQUIPEMENT = NEW.ID_EQUIPEMENT
        AND DATE = NEW.DATE
        AND (NEW.HEURE_DEBUT < HEURE_FIN AND NEW.HEURE_FIN > HEURE_DEBUT);

      -- Si le nombre dépasse la quantité disponible, on empêche la réservation
      IF current_resa >= max_qty THEN
         SIGNAL SQLSTATE '45000'
         SET MESSAGE_TEXT = 'Aucun équipement disponible pour ce créneau.';
      END IF;
   END IF;
END;;

DELIMITER ;;

CREATE TRIGGER before_insert_reserver_check_cours
BEFORE INSERT ON RESERVER
FOR EACH ROW
BEGIN
   DECLARE max_places INT DEFAULT 0;
   DECLARE current_resa INT DEFAULT 0;

   IF NEW.ID_COURS IS NOT NULL THEN
      -- Récupère le nombre de places disponibles pour ce cours
      SELECT NOMBRE_PLACES INTO max_places
      FROM COURS
      WHERE ID_COURS = NEW.ID_COURS;

      -- Compte le nombre de réservations déjà faites pour ce cours
      SELECT COUNT(*) INTO current_resa
      FROM RESERVER
      WHERE ID_COURS = NEW.ID_COURS;

      -- Si le cours est plein, empêcher la réservation
      IF current_resa >= max_places THEN
         SIGNAL SQLSTATE '45000'
         SET MESSAGE_TEXT = 'Plus de places disponibles pour ce cours.';
      END IF;
   END IF;
END;;

DELIMITER ;


-- INSERTIONS
INSERT INTO TYPE_USER (ID_TYPE_USER, LIBELLE_TYPE_USER) VALUES
('A', 'Administrateur'),
('C', 'Coach'),
('M', 'Membre');

INSERT INTO TYPE_SALLE (ID_TYPE_SALLE, LIBELLE_TYPE_SALLE) VALUES
('S', 'Salle de sport'),
('C', 'Salle de cours'),
('R', 'Salle de repos');

INSERT INTO TYPE_CAPTEUR (ID_TYPE_CAPTEUR, LIBELLE_TYPE_CAPTEUR) VALUES
('C', 'Caméra'),
('D', 'Capteur Température/Humidité DHT11'),
('R', 'Lecteur RFID');

INSERT INTO CAPTEURS (ID_TYPE_CAPTEUR, LIBELLE_CAPTEUR, MESURE_1, MESURE_2) VALUES
('C', 'Caméra principale', 0, 0),
('D', 'Capteur Temp/Hum DHT11 - Zone Cardio', 22.5, 55.2),
('R', 'Lecteur RFID Entrée', 0, 0);

INSERT INTO SALLES (ID_TYPE_SALLE, ID_CAPTEUR, NOM_SALLE) VALUES
('S', 1, 'Salle Musculation'),
('C', 2, 'Salle Yoga'),
('R', 3, 'Salon Détente');

INSERT INTO EQUIPEMENTS (TYPE_EQUIPEMENT, QUANTITE_DISPONIBLE) VALUES
('Tapis de course', 3),
('Vélo', 5),
('Banc de musculation', 2),
('Haltères 20kg', 10);

INSERT INTO COURS (TYPE_COURS, DATE_COURS, HEURE_DEBUT, HEURE_FIN, NOMBRE_PLACES) VALUES
('Yoga', '2025-05-01', '10:00:00', '11:00:00', 10),
('Crossfit', '2025-05-02', '14:00:00', '15:00:00', 15),
('Pilates', '2025-05-03', '09:00:00', '10:00:00', 8);

INSERT INTO USERS (ID_SALLE, ID_TYPE_USER, NOM_USER, PRENOM_USER, GENRE_USER, MOT_DE_PASSE_USER) VALUES
(1, 'A', 'Dupont', 'Alice', 'F', 'hashed_pwd1'),
(1, 'C', 'Martin', 'Luc', 'M', 'hashed_pwd2'),
(2, 'M', 'Durand', 'Emma', 'F', 'hashed_pwd3'),
(2, 'M', 'Lemoine', 'Pierre', 'M', 'hashed_pwd4'),
(3, 'M', 'Moreau', 'Chloé', 'F', 'hashed_pwd5');

INSERT INTO RESERVER (ID_USER, ID_EQUIPEMENT, ID_COURS, DATE, HEURE_DEBUT, HEURE_FIN) VALUES
(1, 1, NULL, '2025-05-01', '08:00:00', '09:00:00'),
(2, NULL, 2, '2025-05-02', '14:00:00', '15:00:00'),
(3, 2, NULL, '2025-05-01', '10:00:00', '11:00:00'),
(4, NULL, 3, '2025-05-03', '09:00:00', '10:00:00'),
(5, 3, NULL, '2025-05-01', '11:00:00', '12:00:00');
